### ISSUE TITLE
notification alert about unsuccessful login is not shown

### ISSUE THREAD

**Issue by segrey11** [yeti-switch/yeti-client#30]
Open auth page
Write incorrect login/pass
Press login.

No any notifications are shown.

**Comment by andrewmiroshnichenko** [comment]
@segrey11 be aware that this is related to inconsistent API responses. 
For example: expired token causes API response 401 with body, containing error message.
But incorrect login/pass causes 404 response with no body (which is quite wrong, IMHO).
I asked @dmitry-sinina to unify API responses first, and then we'll be able to improve code that handles errors.
